name: Manage Participants

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform (upload or verify)'
        required: true
        default: 'verify'
        type: choice
        options:
          - upload
          - verify
      college:
        description: 'College to process'
        required: true
        default: 'CMRIT'
        type: choice
        options:
          - CMRIT
      batch:
        description: 'Batch to process'
        required: true
        default: '_2025'
        type: choice
        options:
          - _2025
          - _2026
          - _2027
      debug:
        description: 'Enable debug mode with verbose logging'
        required: false
        default: 'false'
        type: boolean

jobs:
  setup:
    uses: ./.github/workflows/reusable-actions.yml
    secrets: inherit
    
  manage-participants:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Download environment setup
        uses: actions/download-artifact@v4
        with:
          name: environment-setup
          
      - name: Upload participants
        if: ${{ github.event.inputs.action == 'upload' }}
        run: |
          debug_flag="${{ github.event.inputs.debug == 'true' && '--debug' || '' }}"
          
          # Upload participants
          python main.py $debug_flag upload-users \
            --college ${{ github.event.inputs.college }} \
            --batch ${{ github.event.inputs.batch }}
            
      - name: Verify participants
        if: ${{ github.event.inputs.action == 'verify' }}
        run: |
          debug_flag="${{ github.event.inputs.debug == 'true' && '--debug' || '' }}"
          
          # Verify participants
          python main.py $debug_flag verify-users \
            --college ${{ github.event.inputs.college }} \
            --batch ${{ github.event.inputs.batch }}
            
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: participant-management-logs-${{ github.run_id }}
          path: logfile.log
          retention-days: 7