name: Weekly Data Pipeline

on:
  schedule:
    # Run at 00:00 on Sunday
    - cron: '0 0 * * 0'
  workflow_dispatch:
    inputs:
      college:
        description: 'College to process'
        required: true
        default: 'CMRIT'
        type: choice
        options:
          - CMRIT
      batch:
        description: 'Batch to process'
        required: true
        default: '_2025'
        type: choice
        options:
          - _2025
          - _2026
          - _2027
      platforms:
        description: 'Platforms to scrape'
        required: true
        default: 'ALL'
        type: choice
        options:
          - ALL
          - 'CODECHEF CODEFORCES'
          - 'CODECHEF LEETCODE'
          - 'CODEFORCES LEETCODE'
          - 'CODECHEF CODEFORCES LEETCODE'
          - 'HACKERRANK GEEKSFORGEEKS'
          - 'CODECHEF CODEFORCES HACKERRANK GEEKSFORGEEKS LEETCODE'
      debug:
        description: 'Enable debug mode with verbose logging'
        required: false
        default: 'false'
        type: boolean

jobs:
  setup:
    uses: ./.github/workflows/reusable-actions.yml
    secrets: inherit
    
  run-pipeline:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Create .env file
        run: |
          cp .env.example .env
          # Update the .env file with actual credentials
          sed -i 's|DB_MONGODB_URI=.*|DB_MONGODB_URI=${{ secrets.MONGODB_URI }}|g' .env
          sed -i 's|DB_MONGODB_PASSWORD=.*|DB_MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }}|g' .env
          sed -i 's|API_CODEFORCES_KEY=.*|API_CODEFORCES_KEY=${{ secrets.API_CODEFORCES_KEY }}|g' .env
          sed -i 's|API_CODEFORCES_SECRET=.*|API_CODEFORCES_SECRET=${{ secrets.API_CODEFORCES_SECRET }}|g' .env
          sed -i 's|API_CODECHEF_CLIENT_ID=.*|API_CODECHEF_CLIENT_ID=${{ secrets.API_CODECHEF_CLIENT_ID }}|g' .env
          sed -i 's|API_CODECHEF_CLIENT_SECRET=.*|API_CODECHEF_CLIENT_SECRET=${{ secrets.API_CODECHEF_CLIENT_SECRET }}|g' .env
          sed -i 's|API_GFG_USERNAME=.*|API_GFG_USERNAME=${{ secrets.API_GFG_USERNAME }}|g' .env
          sed -i 's|API_GFG_PASSWORD=.*|API_GFG_PASSWORD=${{ secrets.API_GFG_PASSWORD }}|g' .env
          
      - name: Run full pipeline
        run: |
          platforms="${{ github.event_name == 'workflow_dispatch' && github.event.inputs.platforms || 'ALL' }}"
          debug_flag="${{ github.event_name == 'workflow_dispatch' && (github.event.inputs.debug == 'true' && '--debug' || '') || '' }}"
          
          # Create output directory
          mkdir -p pipeline_output
          
          # Run the pipeline
          python main.py $debug_flag run-pipeline \
            --college ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.college || 'CMRIT' }} \
            --batch ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.batch || '_2025' }} \
            --platforms $platforms \
            --output pipeline_output/leaderboard_${{ github.event_name == 'workflow_dispatch' && github.event.inputs.college || 'CMRIT' }}_${{ github.event_name == 'workflow_dispatch' && github.event.inputs.batch || '_2025' }}.xlsx \
            --charts
            
      - name: Upload leaderboard
        uses: actions/upload-artifact@v3
        with:
          name: leaderboard-${{ github.event_name == 'workflow_dispatch' && github.event.inputs.college || 'CMRIT' }}-${{ github.event_name == 'workflow_dispatch' && github.event.inputs.batch || '_2025' }}-${{ github.run_id }}
          path: pipeline_output/leaderboard_${{ github.event_name == 'workflow_dispatch' && github.event.inputs.college || 'CMRIT' }}_${{ github.event_name == 'workflow_dispatch' && github.event.inputs.batch || '_2025' }}.xlsx
          retention-days: 30
          
      - name: Upload logs
        uses: actions/upload-artifact@v3
        with:
          name: logs-${{ github.event_name == 'workflow_dispatch' && github.event.inputs.college || 'CMRIT' }}-${{ github.event_name == 'workflow_dispatch' && github.event.inputs.batch || '_2025' }}-${{ github.run_id }}
          path: logfile.log
          retention-days: 7